# !/usr/bin/python3 Testing basic paho-mqtt implmentation for publishing MQTT messages internally, i.e.,
# data generated by the Pi that's also running the emon server **** Needs to run with Python 3 ******

import paho.mqtt.publish as publish
# if necesssary, install with 'pip3 install paho-mqtt' (but should be already
# installed in the emon server)

# Code goes here that collects and calibrates readings from sensors

# Finalized readings to send to emon
Moisture1 = 77
GPM1 = 211
Temperature1 = 19.3
Rotation1_RPM = 0.3

# publish multiple messages - this is a Python list of dict elements!
# topic parts: "emon" is required; "Sprinkler1" is a Node-name; "Moisture1" "GPM1", etc are data labels
msg = [{'topic': "emon/Sprinkler1/Moisture1", 'payload': Moisture1},
        {'topic': "emon/Sprinkler1/GPM1", 'payload': GPM1},
        {'topic': "emon/Sprinkler1/Temperature1", 'payload': Temperature1},
        {'topic': "emon/Sprinkler1/Rotation1_RPM", 'payload': Rotation1_RPM}]

# Publish them via MQTT using the multiple method
# Do not need to specify a host since publishing internally
publish.multiple(msg,auth={'username':"emonpi",'password':"emonpimqtt2016"})
